spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/povs
    username: aymane
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082

application:
  security:
    jwt:
      secret-key: 6D597133743677397A24432646294A404D635166546A576E5A7234753778214125442A472D4B6150645267556B58703273357638792F423F4528482B4D625165
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days